"""
Lobster 加密打包构建脚本
========================
完整流程：复制项目 → 编译 .py → .pyc 并删除源码 → PyInstaller 编译启动器 → 输出分发包

保护机制：
  1. 将 .py 编译为同级 .pyc（字节码）
  2. 用极小 loader stub 替换 .py 源码，保持文件路径执行/动态加载兼容
  3. 编译启动器 EXE；注意 .pyc 不是不可逆强加密

所有操作在 _pack_exe_test/staging/ 临时目录中进行，绝不修改原始文件。

用法：
    python _pack_exe_test/build_encrypted_dist.py
    python _pack_exe_test/build_encrypted_dist.py --skip-encrypt  # 跳过加密（调试用）
"""
from __future__ import annotations

import compileall
import os
import platform
import py_compile
import shutil
import subprocess
import sys
import time
import zipfile
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
STAGING_DIR = SCRIPT_DIR / "staging"
OUTPUT_DIR = SCRIPT_DIR / "output"
ARCHIVE_ROOT_NAME = "lobster_online"
FACTORY_CONFIGURATOR_EXE = "OEM\u914d\u7f6e\u542f\u52a8\u5668.exe"
BRAND_LAUNCHER_EXES = {
    "\u5fc5\u706b\u667a\u80fdAI.exe",
    "\u5fc5\u706bAI\u5458\u5de5.exe",
}

PYTHON = str(PROJECT_ROOT / "python" / "python.exe")
PYINSTALLER = str(PROJECT_ROOT / "python" / "Scripts" / "pyinstaller.exe")


def ensure_running_with_bundled_python() -> None:
    """Build .pyc with the same Python runtime that ships in the package."""
    bundled = Path(PYTHON)
    if not bundled.is_file():
        return
    try:
        if Path(sys.executable).resolve() == bundled.resolve():
            return
    except Exception:
        pass
    if os.environ.get("LOBSTER_ENCRYPTED_BUILD_REEXEC") == "1":
        return
    env = os.environ.copy()
    env["LOBSTER_ENCRYPTED_BUILD_REEXEC"] = "1"
    print(f"[BUILD] Re-launching with bundled Python for .pyc compatibility: {bundled}")
    raise SystemExit(
        subprocess.call(
            [str(bundled), str(Path(__file__).resolve()), *sys.argv[1:]],
            cwd=str(PROJECT_ROOT),
            env=env,
        )
    )

DIRS_TO_COPY = [
    "backend",
    "desktop",
    "mcp",
    "static",
    "publisher",
    "scripts",
    "openclaw",
    "skills",
]

RUNTIME_DIRS_TO_COPY = [
    "python",
    "deps",
    "nodejs",
]

FILES_TO_COPY = [
    "install.bat",
    "install_slim.bat",
    "start.bat",
    "stop.bat",
    "run_backend.bat",
    "run_mcp.bat",
    "fix_mcp.bat",
    "requirements.txt",
    ".env",
    ".env.example",
    "CLIENT_CODE_VERSION.json",
    "必火智能AI.exe",
    "必火AI员工.exe",
    "upstream_urls.json",
    "skill_registry.json",
]

DIRS_TO_ENCRYPT = [
    "backend",
    "desktop",
    "mcp",
    "publisher",
    "scripts",
    "skills",
    "static",
]

# 用同名 .pyc 承载真实代码；.py 只保留极小 loader。
# 这样可以同时兼容：
#   - python path/to/script.py
#   - import package.module
#   - importlib.util.spec_from_file_location(..., "script.py")
PYC_LOADER_STUB = """# Auto-generated by _pack_exe_test/build_encrypted_dist.py.
# Real code is stored in the sibling .pyc file.
from __future__ import annotations
import importlib.machinery as _lobster_machinery
import pathlib as _lobster_pathlib
import sys as _lobster_sys
import types as _lobster_types
_lobster_pyc = _lobster_pathlib.Path(__file__).with_suffix(".pyc")
_lobster_loader = _lobster_machinery.SourcelessFileLoader(__name__, str(_lobster_pyc))
_lobster_module = _lobster_sys.modules.get(__name__)
if _lobster_module is None:
    _lobster_module = _lobster_types.ModuleType(__name__)
    _lobster_module.__file__ = __file__
    _lobster_module.__loader__ = _lobster_loader
    _lobster_module.__package__ = __package__
    _lobster_sys.modules[__name__] = _lobster_module
_lobster_loader.exec_module(_lobster_module)
globals().update(_lobster_module.__dict__)
"""

# 不复制的大型运行时目录（用户侧通过 install.bat 安装或已预装）
SKIP_DIRS = {
    "assets", "browser_data", "logs", "dist",
    "_pack_exe_test", ".pack_python_shim", ".git", ".cursor",
    "__pycache__", "build_exe", "dist_exe", ".venv",
    "temp_test_inputs", "temp_test_outputs",
}

SKIP_FILES = {
    ".installed", "launcher.log", "launcher_crash.log",
    "backend.log", "mcp.log",
}

COMMON_SKIP_DIR_NAMES = {
    "__pycache__",
    ".git",
    ".venv",
    "venv",
    "env",
    ".DS_Store",
}

COMMON_SKIP_FILE_SUFFIXES = (
    ".pyc",
    ".pyo",
    ".log",
    ".db",
    ".db-journal",
    ".sqlite",
    ".sqlite3",
    ".tmp",
    ".temp",
)

OPENCLAW_SKIP_DIR_NAMES = {
    ".openclaw",
    ".node_compile_cache",
    "agents",
    "browser",
    "cron",
    "delivery-queue",
    "devices",
    "identity",
    "logs",
    "memory",
    "openclaw-weixin",
    "tasks",
    "user_memory",
}

OPENCLAW_SKIP_FILE_NAMES = {
    ".env",
    ".channel_fallback.json",
    ".lobster_plugin_state_backup.json",
    ".weixin_login_last.json",
    "update-check.json",
}

SKILL_RUNTIME_DIR_NAMES = {"runs", "job_runs", "output", "cache"}

REMOVED_3D_WHEEL_PREFIXES = (
    "filelock-",
    "flatbuffers-",
    "fsspec-",
    "imageio-",
    "jinja2-",
    "jsonschema-",
    "jsonschema_specifications-",
    "lazy_loader-",
    "llvmlite-",
    "markupsafe-",
    "mpmath-",
    "networkx-",
    "numba-",
    "onnxruntime-",
    "opencv_python-",
    "platformdirs-",
    "pooch-",
    "pymeshfix-",
    "pymatting-",
    "referencing-",
    "rembg-",
    "rpds_py-",
    "scikit_image-",
    "scipy-",
    "segment_anything-",
    "shapely-",
    "sympy-",
    "tifffile-",
    "torch-",
    "torchvision-",
    "trimesh-",
)

REMOVED_3D_SITE_PACKAGE_PREFIXES = (
    "cv2",
    "filelock",
    "flatbuffers",
    "fsspec",
    "functorch",
    "imageio",
    "isympy.",
    "jinja2",
    "jsonschema",
    "jsonschema_specifications",
    "lazy_loader",
    "llvmlite",
    "llvmlite.libs",
    "markupsafe",
    "mpmath",
    "networkx",
    "numba",
    "onnxruntime",
    "opencv_python",
    "platformdirs",
    "pooch",
    "pymatting",
    "pymeshfix",
    "pymeshfix.libs",
    "referencing",
    "rembg",
    "rpds",
    "rpds_py",
    "scikit_image",
    "scipy",
    "scipy.libs",
    "segment_anything",
    "shapely",
    "shapely.libs",
    "skimage",
    "sympy",
    "tifffile",
    "torch",
    "torchgen",
    "torchvision",
    "trimesh",
)

REMOVED_3D_SCRIPT_NAMES = {
    "isympy.exe",
    "numba",
    "rembg.exe",
    "torchfrtrace.exe",
    "torchrun.exe",
    "trimesh.exe",
}

OPENCLAW_DEFAULT_WORKSPACE_FILES = (
    "AGENTS.md",
    "BOOTSTRAP.md",
    "HEARTBEAT.md",
    "IDENTITY.md",
    "LOBSTER_CHAT_POLICY_INTRO.md",
    "LOBSTER_CHAT_POLICY_TOOLS.md",
    "SOUL.md",
    "TOOLS.md",
    "USER.md",
)

OPENCLAW_POLICY_FILES = (
    "LOBSTER_CHAT_POLICY_INTRO.md",
    "LOBSTER_CHAT_POLICY_TOOLS.md",
)


def log(msg: str):
    print(f"[BUILD] {msg}")


def step(n: int, total: int, msg: str):
    print(f"\n{'='*50}")
    print(f"  Step {n}/{total}: {msg}")
    print(f"{'='*50}")


def clean_staging():
    if STAGING_DIR.exists():
        log(f"清理旧 staging 目录: {STAGING_DIR}")
        shutil.rmtree(STAGING_DIR)
        if STAGING_DIR.exists():
            raise RuntimeError(f"无法清理 staging 目录，请关闭占用文件后重试: {STAGING_DIR}")
    STAGING_DIR.mkdir(parents=True, exist_ok=True)


def _rel_posix(path: Path) -> str:
    return path.as_posix().strip("/")


def _should_skip_rel(rel_posix: str, *, is_dir: bool, factory_oem: bool = False) -> bool:
    rel_posix = _rel_posix(Path(rel_posix))
    if not rel_posix:
        return False
    parts = rel_posix.split("/")
    name = parts[-1]
    lower = rel_posix.lower()

    if name in COMMON_SKIP_DIR_NAMES:
        return True
    if name in SKIP_FILES:
        return True
    if name == ".env" and rel_posix != ".env":
        return True
    if name.endswith(".bak") or ".bak." in name:
        return True
    if not is_dir and lower.endswith(COMMON_SKIP_FILE_SUFFIXES):
        return True

    if rel_posix == ".installed":
        return True
    if rel_posix.startswith(("assets/", "browser_data/", "logs/", "chat_storage/", ".updates/", "_lobster_runtime/")):
        return True
    if rel_posix.startswith(("static/uploads/", "static/hifly_previews/")):
        return True
    if factory_oem and rel_posix.startswith("static/branding/cache/"):
        return True
    if rel_posix.startswith("desktop/webview2/fixed-runtime/"):
        return True
    if rel_posix.startswith("models/sam/"):
        return True
    if (
        len(parts) >= 4
        and parts[0] == "python"
        and parts[1].lower() == "lib"
        and parts[2].lower() == "site-packages"
        and parts[3].lower().startswith(REMOVED_3D_SITE_PACKAGE_PREFIXES)
    ):
        return True
    if (
        len(parts) >= 3
        and parts[0] == "python"
        and parts[1].lower() == "scripts"
        and parts[2].lower() in REMOVED_3D_SCRIPT_NAMES
    ):
        return True
    if (
        len(parts) >= 3
        and parts[0] == "deps"
        and parts[1] == "wheels"
        and name.lower().startswith(REMOVED_3D_WHEEL_PREFIXES)
    ):
        return True

    if parts[0] == "openclaw":
        if len(parts) >= 2:
            child = parts[1]
            if is_dir and (child == "workspace" or child.startswith("workspace-")):
                return True
            if is_dir and child in OPENCLAW_SKIP_DIR_NAMES:
                return True
        if name in OPENCLAW_SKIP_FILE_NAMES:
            return True

    # skills/<skill_id>/<runtime_dir>/... 是本机任务执行结果，不进入分发包。
    if len(parts) >= 3 and parts[0] == "skills" and parts[2] in SKILL_RUNTIME_DIR_NAMES:
        return True

    return False


def _copy_ignore_for(top_name: str, *, factory_oem: bool = False):
    top_src = (PROJECT_ROOT / top_name).resolve()

    def _ignore(dir_path: str, names: list[str]) -> set[str]:
        ignored: set[str] = set()
        base = Path(dir_path).resolve()
        try:
            base_rel = base.relative_to(top_src)
        except ValueError:
            base_rel = Path()
        for name in names:
            full = base / name
            rel = Path(top_name) / base_rel / name
            if _should_skip_rel(
                rel.as_posix(),
                is_dir=full.is_dir(),
                factory_oem=factory_oem,
            ):
                ignored.add(name)
        return ignored

    return _ignore


def copy_project(include_runtime: bool = False, *, factory_oem: bool = False):
    """复制必要文件到 staging 目录"""
    dirs_to_copy = list(DIRS_TO_COPY)
    if include_runtime:
        dirs_to_copy.extend(RUNTIME_DIRS_TO_COPY)

    for d in dirs_to_copy:
        src = PROJECT_ROOT / d
        dst = STAGING_DIR / d
        if src.exists():
            log(f"  复制目录: {d}/")
            shutil.copytree(src, dst, ignore=_copy_ignore_for(d, factory_oem=factory_oem))
        else:
            log(f"  [SKIP] 目录不存在: {d}/")

    files_to_copy = list(FILES_TO_COPY)
    if factory_oem:
        files_to_copy = [
            name
            for name in files_to_copy
            if name != ".env" and name not in BRAND_LAUNCHER_EXES
        ]
        files_to_copy.append(FACTORY_CONFIGURATOR_EXE)

    for f in files_to_copy:
        src = PROJECT_ROOT / f
        dst = STAGING_DIR / f
        if src.exists():
            shutil.copy2(src, dst)
        else:
            log(f"  [SKIP] 文件不存在: {f}")

    _copy_openclaw_workspace_defaults()


def _openclaw_default_candidates(filename: str) -> list[Path]:
    base = PROJECT_ROOT / "openclaw"
    candidates = [
        base / "global_workspace_defaults" / filename,
        base / "workspace" / filename,
        base / "workspace-lobster-sutui-deepseek-chat" / filename,
        base / "workspace-lobster-sutui-gpt-4o-mini" / filename,
    ]
    candidates.extend(sorted(base.glob(f"workspace-*/{filename}")))
    return candidates


def _first_existing(paths: list[Path]) -> Path | None:
    for path in paths:
        if path.is_file():
            return path
    return None


def _copy_openclaw_workspace_defaults() -> None:
    """只放产品默认工作区文件，不复制用户 workspace / memory / sessions。"""
    oc_dst = STAGING_DIR / "openclaw"
    if not (PROJECT_ROOT / "openclaw").is_dir():
        return
    defaults_dst = oc_dst / "global_workspace_defaults"
    workspace_dst = oc_dst / "workspace"
    for name in OPENCLAW_DEFAULT_WORKSPACE_FILES:
        src = _first_existing(_openclaw_default_candidates(name))
        if src is None:
            log(f"  [WARN] OpenClaw 默认工作区文件缺失: {name}")
            continue
        defaults_dst.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, defaults_dst / name)
        if name in OPENCLAW_POLICY_FILES:
            workspace_dst.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, workspace_dst / name)


def compile_and_strip(skip: bool = False):
    """将 .py 编译为同名 .pyc，并把 .py 替换为 loader stub。"""
    if skip:
        log("跳过编译（--skip-encrypt）")
        return

    total_stubbed = 0
    failures: list[tuple[Path, str]] = []

    for d in DIRS_TO_ENCRYPT:
        src_dir = STAGING_DIR / d
        if not src_dir.exists():
            continue

        py_files = list(src_dir.rglob("*.py"))
        if not py_files:
            continue

        log(f"  编译 {d}/ ({len(py_files)} 个 .py 文件)...")

        for py_file in py_files:
            target_pyc = py_file.with_suffix(".pyc")
            try:
                dfile = str(py_file.relative_to(STAGING_DIR)).replace(os.sep, "/")
                py_compile.compile(
                    str(py_file),
                    cfile=str(target_pyc),
                    dfile=dfile,
                    doraise=True,
                    optimize=0,
                )
                py_file.write_text(PYC_LOADER_STUB, encoding="utf-8", newline="\n")
                total_stubbed += 1
            except Exception as exc:
                failures.append((py_file, str(exc)))

        for cache_dir in src_dir.rglob("__pycache__"):
            shutil.rmtree(cache_dir, ignore_errors=True)

        log(f"  [OK] {d}/ 编译完成")

    if failures:
        for path, err in failures[:20]:
            log(f"  [ERR] 编译失败: {path} -> {err}")
        raise RuntimeError(f"{len(failures)} 个 .py 文件编译失败，已停止打包以避免源码泄露")

    log(f"  已保护 {total_stubbed} 个 .py：真实代码在同名 .pyc，.py 为 loader stub")


def prepare_desktop_launcher_exe(*, factory_oem: bool = False):
    """Validate the appropriate desktop entry for branded or factory packages."""
    if factory_oem:
        configurator = STAGING_DIR / FACTORY_CONFIGURATOR_EXE
        if configurator.is_file():
            size_kb = configurator.stat().st_size / 1024
            log(f"  [OK] {FACTORY_CONFIGURATOR_EXE} ({size_kb:.1f} KB)")
            return True
        log(f"[ERR] {FACTORY_CONFIGURATOR_EXE} missing; cannot build factory package")
        return False
    exe_path = STAGING_DIR / "必火智能AI.exe"
    if not exe_path.exists():
        src = PROJECT_ROOT / "必火智能AI.exe"
        if src.exists():
            shutil.copy2(src, exe_path)

    legacy_lobster = STAGING_DIR / "lobster.exe"
    if legacy_lobster.exists():
        legacy_lobster.unlink()

    if exe_path.exists():
        size_kb = exe_path.stat().st_size / 1024
        log(f"  [OK] 必火智能AI.exe ({size_kb:.1f} KB)")
        return True

    log("[ERR] 必火智能AI.exe 不存在，不能改变正式启动入口")
    return False


def calculate_size():
    """计算 staging 目录总大小"""
    total = 0
    for p in STAGING_DIR.rglob("*"):
        if p.is_file():
            total += p.stat().st_size
    return total


def create_output_zip(include_runtime: bool = False, *, factory_oem: bool = False):
    """创建最终分发 zip 包"""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    timestamp = time.strftime("%Y%m%d_%H%M%S")
    if factory_oem:
        suffix = "_factory_runtime" if include_runtime else "_factory"
    else:
        suffix = "_runtime" if include_runtime else ""
    zip_name = f"lobster_desktop{suffix}_{timestamp}"
    zip_path = OUTPUT_DIR / zip_name

    log(f"创建分发包: {zip_path}.zip")
    final_zip = Path(f"{zip_path}.zip")
    if final_zip.exists():
        final_zip.unlink()
    with zipfile.ZipFile(final_zip, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
        for path in STAGING_DIR.rglob("*"):
            if not path.is_file():
                continue
            rel = path.relative_to(STAGING_DIR).as_posix()
            zf.write(path, f"{ARCHIVE_ROOT_NAME}/{rel}")

    if final_zip.exists():
        size_mb = final_zip.stat().st_size / (1024 * 1024)
        log(f"[OK] {final_zip.name} ({size_mb:.1f} MB)")
        return final_zip
    return None


def main():
    ensure_running_with_bundled_python()

    skip_encrypt = "--skip-encrypt" in sys.argv
    if skip_encrypt and os.environ.get("LOBSTER_ALLOW_PLAIN_PACK") != "1":
        raise SystemExit(
            "拒绝生成明文完整版：正式包必须加密；仅本机调试时设置 "
            "LOBSTER_ALLOW_PLAIN_PACK=1"
        )
    include_runtime = "--include-runtime" in sys.argv
    factory_oem = "--factory-oem" in sys.argv
    total_steps = 5

    print("=" * 50)
    print("  Lobster Desktop 加密打包构建")
    print("=" * 50)
    print(f"  项目根: {PROJECT_ROOT}")
    print(f"  输出到: {STAGING_DIR}")
    print(f"  保护:   {'跳过' if skip_encrypt else '编译.pyc+删除源码'}")
    print(f"  运行时: {'包含' if include_runtime else '不包含'}")
    print(f"  工厂包: {'是' if factory_oem else '否'}")
    print()

    # Step 1: 清理
    step(1, total_steps, "清理构建目录")
    clean_staging()

    # Step 2: 复制项目文件
    step(2, total_steps, "复制项目文件到 staging")
    copy_project(include_runtime=include_runtime, factory_oem=factory_oem)
    size = calculate_size()
    log(f"  复制完成: {size / (1024*1024):.1f} MB")

    # Step 3: 编译 Python 代码并删除源码
    step(3, total_steps, "编译 Python 代码 → .pyc 并删除源码")
    compile_and_strip(skip=skip_encrypt)

    # Step 4: 准备正式桌面启动器 EXE
    step(4, total_steps, "准备 必火智能AI.exe 桌面启动器")
    if not prepare_desktop_launcher_exe(factory_oem=factory_oem):
        log("[ERR] 构建失败！")
        sys.exit(1)

    # Step 5: 打包输出
    step(5, total_steps, "创建分发 zip 包")
    staging_size = calculate_size()
    log(f"  staging 目录大小: {staging_size / (1024*1024):.1f} MB")
    zip_file = create_output_zip(
        include_runtime=include_runtime,
        factory_oem=factory_oem,
    )

    print()
    print("=" * 50)
    print("  构建完成！")
    print("=" * 50)
    print()
    print("  分发包内容：")
    print("    - python/           → 嵌入式 Python（install.bat 会检测）")
    print("    - deps/             → ffmpeg + pip wheels")
    print("    - nodejs/           → Node.js + OpenClaw")
    print()
    print("  使用方式：")
    print("    1. 解压分发包到目标目录")
    if include_runtime:
        print("    2. Python、Node/OpenClaw 和离线 wheels 已包含，无需另行准备")
    else:
        print("    2. 将运行时文件放入对应子目录")
    if factory_oem:
        print(f"    3. 双击 {FACTORY_CONFIGURATOR_EXE} 完成品牌配置")
    else:
        print("    3. 双击 必火智能AI.exe（保持正式桌面启动流程）")
    print()
    if zip_file:
        print(f"  分发包路径: {zip_file}")
    print()


if __name__ == "__main__":
    main()
