#!/usr/bin/env python3
"""
打「纯代码」OTA zip（与 scripts/check_client_code_update.py 的 DEFAULT_PATHS 一致）。
默认已含 nodejs/package*.json 与 ensure-npm-cli.mjs、run-npm.mjs、.gitignore（不含 node_modules），
另一机覆盖后需保证安装包自带 node.exe，点微信授权即可在线拉齐依赖。
可选 --with-nodejs-deps：额外打入 nodejs/node_modules 与 .openclaw/npm（离线大块，一般不用于 OTA）。

不含 python/、deps/、browser_chromium/、nodejs 可执行文件；openclaw 不含 workspace* 整目录（避免 .git/ 与用户数据），
但强制纳入「主对话」必需的 openclaw/workspace/LOBSTER_CHAT_POLICY_*.md（与 backend chat 单一事实来源一致）。
logs、OpenClaw 登录态均不打包；根 .env 作为产品配置随 OTA 下发。
openclaw/openclaw.json 属于运行态配置，不随 OTA 覆盖；backend 启动/重启 Gateway 前会按本机 .env 同步必要字段。
默认产物与 pack_slim_zip 一致：写在 lobster_online 的上一级目录（例如 d:\\lobster_online → d:\\）。
"""
from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path

# 与 check_client_code_update.DEFAULT_PATHS 保持一致
OTA_PATHS: tuple[str, ...] = (
    "scripts",
    "backend",
    "desktop",
    "mcp",
    "static",
    "publisher",
    "skills",
    "skill_registry.json",
    "upstream_urls.json",
    ".env",
    "必火智能AI.exe",
    "openclaw",
    "requirements.txt",
    ".env.example",
    "install.bat",
    "start.bat",
    "run_backend.bat",
    "run_mcp.bat",
    "nodejs/package.json",
    "nodejs/package-lock.json",
    "nodejs/ensure-npm-cli.mjs",
    "nodejs/run-npm.mjs",
    "nodejs/.gitignore",
    "nodejs/node_modules/@tencent-weixin/openclaw-weixin",
    # Keep version last so partial OTA failures do not mark the client updated.
    "CLIENT_CODE_VERSION.json",
)

# 与 check_client_code_update.DEFAULT_PATHS_WITH_NODEJS_DEPS 一致（仅在对等清单外加整树时用）
OTA_PATHS_WITH_NODEJS_DEPS: tuple[str, ...] = OTA_PATHS + (
    "nodejs/.openclaw/npm",
    "nodejs/node_modules",
)

ENCRYPTED_OTA_DIRS: tuple[str, ...] = (
    "backend",
    "desktop",
    "mcp",
    "publisher",
    "scripts",
    "skills",
    "static",
)

PYC_LOADER_STUB = """# Auto-generated by scripts/pack_client_code_ota.py --encrypted.
# Real code is stored in the sibling .pyc file.
from __future__ import annotations
import importlib.machinery as _lobster_machinery
import pathlib as _lobster_pathlib
import sys as _lobster_sys
import types as _lobster_types
_lobster_pyc = _lobster_pathlib.Path(__file__).with_suffix(".pyc")
_lobster_loader = _lobster_machinery.SourcelessFileLoader(__name__, str(_lobster_pyc))
_lobster_module = _lobster_sys.modules.get(__name__)
if _lobster_module is None:
    _lobster_module = _lobster_types.ModuleType(__name__)
    _lobster_module.__file__ = __file__
    _lobster_module.__loader__ = _lobster_loader
    _lobster_module.__package__ = __package__
    _lobster_sys.modules[__name__] = _lobster_module
_lobster_loader.exec_module(_lobster_module)
globals().update(_lobster_module.__dict__)
"""

PPT_RUNTIME_WHEEL_PATTERNS: tuple[str, ...] = (
    "python_pptx-*.whl",
    "svglib-*.whl",
    "reportlab-*.whl",
    "cssselect2-*.whl",
    "rlpycairo-*.whl",
    "pycairo-*.whl",
    "freetype_py-*.whl",
    "tinycss2-*.whl",
    "webencodings-*.whl",
    "lxml-*-cp312-*-win_amd64.whl",
    "pyyaml-*-cp312-*-win_amd64.whl",
    "pillow-*-cp312-*-win_amd64.whl",
    "xlsxwriter-*.whl",
    "charset_normalizer-*-cp312-*-win_amd64.whl",
    "rich-*.whl",
    "markdown_it_py-*.whl",
    "mdurl-*.whl",
    "pygments-*.whl",
    "typer-*.whl",
    "annotated_doc-*.whl",
    "shellingham-*.whl",
    "colorama-*.whl",
    "openai-*.whl",
    "anyio-*.whl",
    "distro-*.whl",
    "httpx-*.whl",
    "httpcore-*.whl",
    "jiter-*-cp312-*-win_amd64.whl",
    "pydantic-*.whl",
    "pydantic_core-*-cp312-*-win_amd64.whl",
    "tzdata-*.whl",
    "tqdm-*.whl",
    "typing_extensions-*.whl",
    "sniffio-*.whl",
    "certifi-*.whl",
    "idna-*.whl",
    "h11-*.whl",
    "annotated_types-*.whl",
)

DOUYIN_RUNTIME_WHEEL_PATTERNS: tuple[str, ...] = (
    "pandas-*-cp312-*-win_amd64.whl",
    "numpy-*-cp312-*-win_amd64.whl",
    "openpyxl-*.whl",
    "et_xmlfile-*.whl",
    "pymysql-*.whl",
    "python_dateutil-*.whl",
    "six-*.whl",
    "tzdata-*.whl",
)

SKIP_DIR_NAMES = {"__pycache__", ".git"}

# OpenClaw state/runtime directories are intentionally excluded from OTA.
# Product defaults are emitted separately under openclaw/global_workspace_defaults.
_OTA_OPENCLAW_SKIP_DIR_NAMES = {
    ".openclaw",
    ".node_compile_cache",
    "agents",
    "browser",
    "cron",
    "delivery-queue",
    "devices",
    "identity",
    "logs",
    "memory",
    "openclaw-weixin",
    "tasks",
    "user_memory",
}
_OTA_OPENCLAW_SKIP_FILE_NAMES = {
    ".lobster_plugin_state_backup.json",
    ".env",
    ".channel_fallback.json",
    ".weixin_login_last.json",
    "openclaw.json",
    "update-check.json",
}
_OTA_SECRET_REL_PATHS = {
    "openclaw/.lobster_plugin_state_backup.json",
    "openclaw/.env",
    "openclaw/.channel_fallback.json",
    "openclaw/.weixin_login_last.json",
    "openclaw/openclaw.json",
    "openclaw/update-check.json",
}

_OTA_SKIP_DIR_RELS = {
    "desktop/webview2",
}

# 本地调试/抓页面临时目录，非交付代码（曾占 OTA 包约 16MB+）
# skills 下各技能的 runs/job_runs 为执行缓存（音视频等），不应随 OTA 分发（否则单包可膨胀 200MB+）
OTA_SKIP_REL_PREFIXES: tuple[str, ...] = (
    ".updates",
    "scripts/_probe",
    "scripts/ppt_runtime_wheels",
    "scripts/douyin_runtime_wheels",
    "static/uploads",
    "tmp_templates",
    "chat_storage",
)

_OTA_SKIP_SKILLS_DIRS = {"runs", "job_runs", "output", "cache"}
# 爆款 TVC 的最终合并依赖 comfly_veo3_daihuo_video 内置 ffmpeg。
# 其它技能的 tools/ffmpeg 仍按默认跳过，避免 OTA 被无关二进制撑大。
_OTA_ALLOW_SKILLS_TOOL_RELS = {
    "skills/comfly_veo3_daihuo_video/tools/ffmpeg",
}
_OTA_SKIP_SKILLS_TOOL_DIRS = {"ffmpeg"}
_OTA_INCLUDE_SKILLS_TOOL_PREFIXES: tuple[str, ...] = (
    "skills/comfly_veo3_daihuo_video/tools/ffmpeg/",
)

# /chat 从该两文件读 system；此前 OTA 排除整个 workspace 会导致覆盖安装后「无工具提示」、模型不调 MCP
_OTA_OPENCLAW_POLICY_RELS: tuple[str, ...] = (
    "openclaw/workspace/LOBSTER_CHAT_POLICY_INTRO.md",
    "openclaw/workspace/LOBSTER_CHAT_POLICY_TOOLS.md",
)

# Product-trained OpenClaw defaults. Runtime/user memory is never packaged; these
# curated files are copied into openclaw/global_workspace_defaults inside the OTA.
_OTA_OPENCLAW_BUNDLED_DEFAULT_FILENAMES: tuple[str, ...] = (
    "AGENTS.md",
    "BOOTSTRAP.md",
    "HEARTBEAT.md",
    "IDENTITY.md",
    "LOBSTER_CHAT_POLICY_INTRO.md",
    "LOBSTER_CHAT_POLICY_TOOLS.md",
    "SOUL.md",
    "TOOLS.md",
    "USER.md",
)


def _norm(p: str) -> str:
    return p.replace("\\", "/")


_INCLUDE_RUNTIME_WHEEL_DIRS: set[str] = set()
_INCLUDE_PYC_FILES = False


def _skip_file(rel: str) -> bool:
    r = _norm(rel).lower()
    nr = _norm(rel)
    if any(nr.startswith(p) for p in _OTA_INCLUDE_SKILLS_TOOL_PREFIXES):
        return False
    if r in _OTA_SECRET_REL_PATHS:
        return True
    if r.endswith(".pyc") and not _INCLUDE_PYC_FILES:
        return True
    parts = r.split("/")
    if "__pycache__" in parts:
        return True
    if any(
        nr.startswith(p)
        for p in OTA_SKIP_REL_PREFIXES
        if p not in _INCLUDE_RUNTIME_WHEEL_DIRS
    ):
        return True
    if any(r.startswith(p + "/") or r == p for p in _OTA_SKIP_DIR_RELS):
        return True
    if len(parts) >= 3 and parts[0] == "skills" and parts[2] in _OTA_SKIP_SKILLS_DIRS:
        return True
    if (
        len(parts) >= 4
        and parts[0] == "skills"
        and parts[2] == "tools"
        and parts[3] in _OTA_SKIP_SKILLS_TOOL_DIRS
        and not any(r.startswith(allow + "/") or r == allow for allow in _OTA_ALLOW_SKILLS_TOOL_RELS)
    ):
        return True
    return False


def _add_tree(zf: zipfile.ZipFile, root: Path, rel_dir: str) -> None:
    base = root / rel_dir.replace("/", os.sep)
    if not base.exists():
        return
    if base.is_file():
        if _skip_file(rel_dir):
            return
        if rel_dir not in zf.NameToInfo:
            zf.write(base, rel_dir)
        return
    for dirpath, dirnames, filenames in os.walk(base):
        rel_here = _norm(os.path.relpath(dirpath, str(root)))
        dirnames[:] = [
            d
            for d in dirnames
            if d not in SKIP_DIR_NAMES
            and not any(
                _norm(os.path.join(rel_here, d)).startswith(p)
                for p in OTA_SKIP_REL_PREFIXES
                if p not in _INCLUDE_RUNTIME_WHEEL_DIRS
            )
            and _norm(os.path.join(rel_here, d)).lower() not in _OTA_SKIP_DIR_RELS
            and not (
                not any(
                    _norm(os.path.join(rel_here, d)).startswith(p.rstrip("/"))
                    for p in _OTA_INCLUDE_SKILLS_TOOL_PREFIXES
                )
                and rel_here.startswith("skills/")
                and rel_here.count("/") == 2
                and rel_here.endswith("/tools")
                and d in _OTA_SKIP_SKILLS_TOOL_DIRS
            )
        ]
        for name in filenames:
            full = Path(dirpath) / name
            rel = _norm(os.path.relpath(str(full), str(root)))
            if _skip_file(rel):
                continue
            if rel in zf.NameToInfo:
                continue
            try:
                if full.is_symlink() and not full.exists():
                    print(f"[WARN] 跳过断链: {rel}")
                    continue
                zf.write(full, rel)
            except OSError as e:
                print(f"[WARN] 跳过无法读取的路径: {rel} ({e})")


def _openclaw_bundled_default_source(root: Path, filename: str) -> Path | None:
    openclaw = root / "openclaw"
    candidates = [
        openclaw / "global_workspace_defaults" / filename,
        openclaw / "workspace" / filename,
        openclaw / "workspace-lobster-sutui-deepseek-chat" / filename,
        openclaw / "workspace-lobster-sutui-gpt-4o-mini" / filename,
    ]
    candidates.extend(sorted(openclaw.glob(f"workspace-*/{filename}")))
    for cand in candidates:
        if cand.is_file():
            return cand
    return None


def _add_openclaw_bundled_defaults(zf: zipfile.ZipFile, root: Path) -> None:
    written = set(zf.namelist())
    for filename in _OTA_OPENCLAW_BUNDLED_DEFAULT_FILENAMES:
        arcname = f"openclaw/global_workspace_defaults/{filename}"
        if arcname in written:
            continue
        src = _openclaw_bundled_default_source(root, filename)
        if src is None:
            print(f"[WARN] missing OpenClaw bundled workspace default: {filename}")
            continue
        zf.write(src, arcname)
        written.add(arcname)


def _add_openclaw(zf: zipfile.ZipFile, root: Path) -> None:
    base = root / "openclaw"
    if not base.is_dir():
        return
    for dirpath, dirnames, filenames in os.walk(base):
        dirnames[:] = [
            d
            for d in dirnames
            if d not in SKIP_DIR_NAMES
            and d != "workspace"
            and not d.startswith("workspace-")
            and d not in _OTA_OPENCLAW_SKIP_DIR_NAMES
        ]
        for name in filenames:
            if name in _OTA_OPENCLAW_SKIP_FILE_NAMES or name.endswith(".bak") or ".bak." in name:
                continue
            full = Path(dirpath) / name
            rel = _norm(os.path.relpath(str(full), str(root)))
            if _skip_file(rel):
                continue
            zf.write(full, rel)

    for rel in _OTA_OPENCLAW_POLICY_RELS:
        src_pol = root / rel.replace("/", os.sep)
        if not src_pol.is_file():
            fallback = None
            name = Path(rel).name
            for cand in sorted((root / "openclaw").glob(f"workspace-*/{name}")):
                if cand.is_file():
                    fallback = cand
                    break
            if fallback is None:
                print(f"[WARN] 缺失聊天策略（请从仓库补齐）: {rel}")
                continue
            src_pol = fallback
            print(f"[WARN] {rel} 缺失，已用 {src_pol.relative_to(root).as_posix()} 兜底打包")
        zf.write(src_pol, rel)

    _add_openclaw_bundled_defaults(zf, root)


def _prepare_runtime_wheels(root: Path, out_rel: str, patterns: tuple[str, ...]) -> list[str]:
    src_dir = root / "deps" / "wheels"
    out_dir = root / out_rel
    if not src_dir.is_dir():
        raise FileNotFoundError(f"missing deps/wheels: {src_dir}")
    out_dir.mkdir(parents=True, exist_ok=True)
    for old in out_dir.iterdir():
        if old.is_file():
            old.unlink()
    picked: dict[str, Path] = {}
    for pattern in patterns:
        matches = sorted(src_dir.glob(pattern), key=lambda p: p.name.lower())
        if not matches:
            raise FileNotFoundError(f"missing runtime wheel matching {pattern}")
        picked[pattern] = matches[-1]
    copied: list[str] = []
    for src in sorted(set(picked.values()), key=lambda p: p.name.lower()):
        dst = out_dir / src.name
        shutil.copy2(src, dst)
        copied.append(dst.relative_to(root).as_posix())
    return copied


def _prepare_ppt_runtime_wheels(root: Path) -> list[str]:
    return _prepare_runtime_wheels(root, "scripts/ppt_runtime_wheels", PPT_RUNTIME_WHEEL_PATTERNS)


def _prepare_douyin_runtime_wheels(root: Path) -> list[str]:
    return _prepare_runtime_wheels(root, "scripts/douyin_runtime_wheels", DOUYIN_RUNTIME_WHEEL_PATTERNS)


def _bundled_python(root: Path) -> Path:
    bundled = root / "python" / "python.exe"
    return bundled if bundled.is_file() else Path(sys.executable)


def _copy_tree_for_encrypted_ota(src: Path, dst: Path, rel: str) -> None:
    if src.is_file():
        if not _skip_file(rel):
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
        return
    for dirpath, dirnames, filenames in os.walk(src):
        rel_here = _norm(os.path.relpath(dirpath, str(src)))
        kept_dirs: list[str] = []
        for d in dirnames:
            if d in SKIP_DIR_NAMES or d == "__pycache__":
                continue
            child_rel = d if rel_here == "." else f"{rel_here}/{d}"
            package_rel = f"{rel}/{child_rel}".replace("\\", "/")
            r = package_rel.lower()
            parts = r.split("/")
            if any(
                package_rel.startswith(p)
                for p in OTA_SKIP_REL_PREFIXES
                if p not in _INCLUDE_RUNTIME_WHEEL_DIRS
            ):
                continue
            if any(r.startswith(p + "/") or r == p for p in _OTA_SKIP_DIR_RELS):
                continue
            if len(parts) >= 3 and parts[0] == "skills" and parts[2] in _OTA_SKIP_SKILLS_DIRS:
                continue
            if (
                len(parts) >= 4
                and parts[0] == "skills"
                and parts[2] == "tools"
                and parts[3] in _OTA_SKIP_SKILLS_TOOL_DIRS
                and not any(r.startswith(allow + "/") or r == allow for allow in _OTA_ALLOW_SKILLS_TOOL_RELS)
            ):
                continue
            kept_dirs.append(d)
        dirnames[:] = kept_dirs
        for name in filenames:
            full = Path(dirpath) / name
            child_rel = name if rel_here == "." else f"{rel_here}/{name}"
            package_rel = f"{rel}/{child_rel}".replace("\\", "/")
            if _skip_file(package_rel):
                continue
            out = dst / child_rel.replace("/", os.sep)
            out.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(full, out)


def _compile_tree_to_pyc(root: Path, target_dirs: tuple[str, ...], python_exe: Path) -> None:
    code = r'''
import os
import py_compile
import sys
from pathlib import Path

root = Path(sys.argv[1]).resolve()
dirs = sys.argv[2:]
stub = """# Auto-generated by scripts/pack_client_code_ota.py --encrypted.
# Real code is stored in the sibling .pyc file.
from __future__ import annotations
import importlib.machinery as _lobster_machinery
import pathlib as _lobster_pathlib
import sys as _lobster_sys
import types as _lobster_types
_lobster_pyc = _lobster_pathlib.Path(__file__).with_suffix(".pyc")
_lobster_loader = _lobster_machinery.SourcelessFileLoader(__name__, str(_lobster_pyc))
_lobster_module = _lobster_sys.modules.get(__name__)
if _lobster_module is None:
    _lobster_module = _lobster_types.ModuleType(__name__)
    _lobster_module.__file__ = __file__
    _lobster_module.__loader__ = _lobster_loader
    _lobster_module.__package__ = __package__
    _lobster_sys.modules[__name__] = _lobster_module
_lobster_loader.exec_module(_lobster_module)
globals().update(_lobster_module.__dict__)
"""
failures = []
count = 0
for rel_dir in dirs:
    base = root / rel_dir
    if not base.exists():
        continue
    for py_file in base.rglob("*.py"):
        try:
            dfile = py_file.relative_to(root).as_posix()
            py_compile.compile(
                str(py_file),
                cfile=str(py_file.with_suffix(".pyc")),
                dfile=dfile,
                doraise=True,
                optimize=0,
            )
            py_file.write_text(stub, encoding="utf-8", newline="\n")
            count += 1
        except Exception as exc:
            failures.append(f"{py_file}: {exc}")
    for cache_dir in base.rglob("__pycache__"):
        import shutil
        shutil.rmtree(cache_dir, ignore_errors=True)
if failures:
    print("\n".join(failures[:20]), file=sys.stderr)
    raise SystemExit(f"{len(failures)} Python files failed to compile")
print(count)
'''
    cmd = [str(python_exe), "-c", code, str(root), *target_dirs]
    subprocess.run(cmd, cwd=str(root), check=True)


def _prepare_encrypted_ota_root(root: Path, paths_tuple: tuple[str, ...]) -> tuple[Path, tempfile.TemporaryDirectory[str]]:
    tmp = tempfile.TemporaryDirectory(prefix="lobster_encrypted_ota_")
    enc_root = Path(tmp.name) / root.name
    enc_root.mkdir(parents=True, exist_ok=True)
    for rel in paths_tuple:
        src = root / rel.replace("/", os.sep)
        dst = enc_root / rel.replace("/", os.sep)
        if not src.exists():
            continue
        if rel == "openclaw":
            shutil.copytree(src, dst, ignore=shutil.ignore_patterns(
                ".env",
                ".openclaw",
                ".node_compile_cache",
                "agents",
                "browser",
                "cron",
                "delivery-queue",
                "devices",
                "identity",
                "logs",
                "memory",
                "openclaw-weixin",
                "tasks",
                "user_memory",
                "workspace",
                "workspace-*",
                "__pycache__",
                "*.pyc",
                "*.pyo",
                "*.log",
                "*.db",
                "*.sqlite",
                "*.sqlite3",
            ))
        else:
            _copy_tree_for_encrypted_ota(src, dst, rel)
    dirs_to_compile = tuple(d for d in ENCRYPTED_OTA_DIRS if (enc_root / d).exists())
    python_exe = _bundled_python(root)
    _compile_tree_to_pyc(enc_root, dirs_to_compile, python_exe)
    return enc_root, tmp


def main() -> int:
    global _INCLUDE_RUNTIME_WHEEL_DIRS, _INCLUDE_PYC_FILES
    ap = argparse.ArgumentParser(description="Pack client-code OTA zip")
    ap.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="lobster_online 根目录",
    )
    ap.add_argument(
        "--out",
        type=Path,
        default=None,
        help="输出 .zip（默认：lobster_online 上一级目录，与 scripts/pack_slim_zip.py 一致）",
    )
    ap.add_argument(
        "--with-nodejs-deps",
        action="store_true",
        help="打入 nodejs/node_modules 与 .openclaw/npm（需本机已 npm install + ensure-npm-cli 跑通）",
    )
    ap.add_argument(
        "--with-ppt-runtime-deps",
        action="store_true",
        help="打入 scripts/ppt_runtime_wheels，并让新版 updater 离线安装 PPT Master 所需依赖",
    )
    ap.add_argument(
        "--with-douyin-runtime-deps",
        action="store_true",
        help="Pack scripts/douyin_runtime_wheels and let updater install Douyin export dependencies offline",
    )
    ap.add_argument(
        "--encrypted",
        action="store_true",
        help="Pack encrypted OTA: ship .py loader stubs plus sibling .pyc files compiled by bundled Python",
    )
    args = ap.parse_args()
    root: Path = args.root.resolve()
    parent = root.parent
    paths_tuple: tuple[str, ...] = OTA_PATHS_WITH_NODEJS_DEPS if args.with_nodejs_deps else OTA_PATHS
    if args.with_ppt_runtime_deps:
        copied = _prepare_ppt_runtime_wheels(root)
        print(f"[ppt-runtime] copied {len(copied)} wheels into scripts/ppt_runtime_wheels")
        _INCLUDE_RUNTIME_WHEEL_DIRS.add("scripts/ppt_runtime_wheels")
        paths_tuple = tuple(p for p in paths_tuple if p != "CLIENT_CODE_VERSION.json") + (
            "scripts/ppt_runtime_wheels",
            "CLIENT_CODE_VERSION.json",
        )
    if args.with_douyin_runtime_deps:
        copied = _prepare_douyin_runtime_wheels(root)
        print(f"[douyin-runtime] copied {len(copied)} wheels into scripts/douyin_runtime_wheels")
        _INCLUDE_RUNTIME_WHEEL_DIRS.add("scripts/douyin_runtime_wheels")
        paths_tuple = tuple(p for p in paths_tuple if p != "CLIENT_CODE_VERSION.json") + (
            "scripts/douyin_runtime_wheels",
            "CLIENT_CODE_VERSION.json",
        )
    if args.out is None:
        ts = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
        suffix_parts = []
        if args.with_nodejs_deps:
            suffix_parts.append("with_nodejs")
        if args.with_ppt_runtime_deps:
            suffix_parts.append("with_ppt_runtime")
        if args.with_douyin_runtime_deps:
            suffix_parts.append("with_douyin_runtime")
        if args.encrypted:
            suffix_parts.append("encrypted")
        suffix = "_" + "_".join(suffix_parts) if suffix_parts else ""
        out = (parent / f"lobster_online_client_code_ota{suffix}_{ts}.zip").resolve()
    else:
        out = args.out.resolve()
    if not root.is_dir():
        print(f"[ERR] root 不是目录: {root}")
        return 1
    if args.with_nodejs_deps:
        nm = root / "nodejs" / "node_modules"
        if not nm.is_dir():
            print(f"[ERR] --with-nodejs-deps 需要已存在的 {nm}")
            return 1
        oc = nm / "openclaw" / "openclaw.mjs"
        if not oc.is_file():
            print(f"[WARN] 未找到 {oc}，目标机可能仍需在线安装依赖")
        cache = root / "nodejs" / ".openclaw" / "npm" / "bin" / "npm-cli.js"
        if not cache.is_file():
            print(
                "[WARN] 缺少 nodejs/.openclaw/npm（可先在本机执行: cd nodejs ; node ensure-npm-cli.mjs），"
                "否则包内无离线 npm 缓存",
            )
    pack_root = root
    encrypted_tmp: tempfile.TemporaryDirectory[str] | None = None
    if args.encrypted:
        _INCLUDE_PYC_FILES = True
        pack_root, encrypted_tmp = _prepare_encrypted_ota_root(root, paths_tuple)
        print(f"[encrypted] staging root: {pack_root}")

    out.parent.mkdir(parents=True, exist_ok=True)
    if out.exists():
        out.unlink()

    packed_manifest_paths: list[str] = []
    with zipfile.ZipFile(out, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for p in paths_tuple:
            rel = p.replace("\\", "/")
            src = pack_root / rel.replace("/", os.sep)
            if not src.exists():
                print(f"[WARN] 缺失，跳过: {rel}")
                continue
            if rel == "openclaw":
                _add_openclaw(zf, root if args.encrypted else pack_root)
            else:
                _add_tree(zf, pack_root, rel)
            packed_manifest_paths.append(rel)

    if encrypted_tmp is not None:
        encrypted_tmp.cleanup()

    h = hashlib.sha256()
    with out.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    digest = h.hexdigest()
    print(out)
    print(f"sha256={digest}")
    ver_path = root / "CLIENT_CODE_VERSION.json"
    _mbuild, _mver = 0, "1.0.0"
    if ver_path.is_file():
        try:
            vd = json.loads(ver_path.read_text(encoding="utf-8"))
            _mbuild = int(vd.get("build", 0))
            _mver = str(vd.get("version", _mver) or _mver).strip() or "1.0.0"
        except Exception:
            pass
    snippet = {
        "build": _mbuild,
        "version": _mver,
        "bundle_url": "https://YOUR_CDN/lobster_client_ota.zip",
        "sha256": digest,
        "paths": packed_manifest_paths,
    }
    if args.encrypted:
        snippet["encrypted"] = True
    hint = (
        "paths 与 DEFAULT_PATHS_WITH_NODEJS_DEPS 对齐（含整包 node 依赖）"
        if args.with_nodejs_deps
        else "paths 与 check_client_code_update.DEFAULT_PATHS 对齐（无 node_modules，点授权在线装）"
    )
    print(f"\n--- manifest 片段（{hint}）---")
    print(json.dumps(snippet, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
